name: Generate Snake üêç

on:
  schedule:
    - cron: "0 0 * * *" # update tiap tengah malam
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub contribution grid snake
        uses: Platane/snk@v3
        with:
          github_user_name: Zharvians
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/ocean-snake.svg?palette=github-dark&color_snake=00FFFF&color_dots=#111111,#00FFFF,#7DF9FF,#0077FF

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
